server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8  
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true  
  datasource:
    url: jdbc:mysql://localhost:3306/maoyan
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.xs.maoyan.model
  mapper-locations: classpath:mapper/*.xml
    